### PR TITLE
Ignore whitespace-only lines

### LINKED ISSUE #1: Cuttlefish chokes on lines with only whitespace characters in the config file
Dear cuttlefish maintainers,
I have discovered an issue in cuttlefish as used in VerneMQ:

The original issue is here:
https://github.com/vernemq/vernemq/issues/1208

The problem is that cuttlefish chokes on lines **which have only whitespace characters (e.g. tabs) in the config file**. This is a particularly difficult issue to debug, as you literally can't see the whitespace. (nano will turn it on if you press Alt + P). 

image

This is what we get currently:
```
jalpine_morpheus | Error generating config with cuttlefish
jalpine_morpheus |   run `vernemq config generate -l debug` for more information.
```
and when drilling down with ```vernemq config generate -l debug```:

```
jalpine_morpheus | escript: exception error: no function clause matching
jalpine_morpheus |                  lists:unzip([[ws,ws],
jalpine_morpheus |                               {["log","console","file"],"./log/console.log"},
jalpine_morpheus |                               {["log","error","file"],"./log/error.log"},
jalpine_morpheus |                               {["log","syslog"],"off"},
jalpine_morpheus |                               {["log","crash"],"on"},
jalpine_morpheus |                               {["log","crash","file"],"./log/crash.log"},
jalpine_morpheus |                               {["log","crash","maximum_message_size"],"64KB"},
jalpine_morpheus |                               {["log","crash","size"],"10MB"},
jalpine_morpheus |                               {["log","crash","rotation"],"$D0"},
jalpine_morpheus |                               {["log","crash","rotation","keep"],"5"},
jalpine_morpheus |                               {["nodename"],"VerneMQ@127.0.0.1"},
jalpine_morpheus |                               {["distributed_cookie"],"vmq"},
jalpine_morpheus |                               {["erlang","async_threads"],"64"},
jalpine_morpheus |                               {["erlang","max_ports"],"262144"},
jalpine_morpheus |                               {["leveldb","maximum_memory","percent"],"70"},
(snip)
jalpine_morpheus |                               {["log","console"],"console"},
jalpine_morpheus |                               {["erlang","distribution","port_range",
jalpine_morpheus |                                 "minimum"],
jalpine_morpheus |                                "9100"},
jalpine_morpheus |                               {["erlang","distribution","port_range",
jalpine_morpheus |                                 "maximum"],
jalpine_morpheus |                                "9109"}],
jalpine_morpheus |                              [["log","console","level"],
jalpine_morpheus |                               ["log","console"],
jalpine_morpheus |                               ["vmq_diversity","auth_redis","enabled"],
jalpine_morpheus |                               ["vmq_diversity","mongodb","database"],
jalpine_morpheus |                               ["vmq_diversity","mongodb","password"],
jalpine_morpheus |                               ["vmq_diversity","mongodb","login"],
jalpine_morpheus |                               ["vmq_diversity","mongodb","port"],
jalpine_morpheus |                               ["vmq_diversity","mongodb","host"],
jalpine_morpheus |                               ["vmq_diversity","auth_mongodb","enabled"],
jalpine_morpheus |                               ["vmq_diversity","mysql","password_hash_method"],
jalpine_morpheus |                               ["vmq_diversity","auth_mysql","enabled"],
jalpine_morpheus |                               ["vmq_diversity","auth_postgres","enabled"],
jalpine_morpheus |                               ["vmq_diversity","script_dir"],
jalpine_morpheus |                               ["vmq_passwd","password_reload_interval"],
jalpine_morpheus |                               ["vmq_passwd","password_file"],
jalpine_morpheus |                               ["vmq_acl","acl_reload_interval"],
jalpine_morpheus |                               ["vmq_acl","acl_file"],
jalpine_morpheus |                               ["metadata_plugin"],
jalpine_morpheus |                               ["plugins","vmq_bridge"],
jalpine_morpheus |                               ["plugins","vmq_webhooks"],
jalpine_morpheus |                               ["plugins","vmq_diversity"],
jalpine_morpheus |                               ["plugins","vmq_acl"],
jalpine_morpheus |                               ["plugins","vmq_passwd"],
jalpine_morpheus |                               ["shared_subscription_policy"],
jalpine_morpheus |                               ["graphite_interval"],
jalpine_morpheus |                               ["graphite_port"],
jalpine_morpheus |                               ["graphite_host"],
jalpine_morpheus |                               ["graphite_enabled"],
jalpine_morpheus |                               ["systree_interval"],
jalpine_morpheus |                               ["systree_enabled"],
jalpine_morpheus |                               ["listener","ws","piclient","mountpoint"],
jalpine_morpheus |                               ["listener","ws","jsclient","mountpoint"],
jalpine_morpheus |                               ["listener","ws","piclient"],
jalpine_morpheus |                               ["listener","ws","jsclient"],
jalpine_morpheus |                               ["listener","nr_of_acceptors"],
jalpine_morpheus |                               ["listener","max_connections"],
jalpine_morpheus |                               ["upgrade_outgoing_qos"],
jalpine_morpheus |                               ["max_message_size"],
jalpine_morpheus |                               ["max_offline_messages"],
jalpine_morpheus |                               ["max_online_messages"],
jalpine_morpheus |                               ["max_inflight_messages"],
jalpine_morpheus |                               ["allow_multiple_sessions"],
jalpine_morpheus |                               ["allow_unsubscribe_during_netsplit"],
jalpine_morpheus |                               ["allow_subscribe_during_netsplit"],
jalpine_morpheus |                               ["allow_publish_during_netsplit"],
jalpine_morpheus |                               [[...]],
jalpine_morpheus |                               [...]],
jalpine_morpheus |                               [...]|...]) (lists.erl, line 402)
jalpine_morpheus |   in function  cuttlefish_conf:file/1 (/vernemq-build/_build/default/lib/cuttlefish/src/cuttlefish_conf.erl, line 74)
jalpine_morpheus |   in call from cuttlefish_conf:'-files/1-fun-1-'/2 (/vernemq-build/_build/default/lib/cuttlefish/src/cuttlefish_conf.erl, line 45)
jalpine_morpheus |   in call from lists:foldl/3 (lists.erl, line 1263)
jalpine_morpheus |   in call from cuttlefish_conf:files/1 (/vernemq-build/_build/default/lib/cuttlefish/src/cuttlefish_conf.erl, line 43)
jalpine_morpheus |   in call from cuttlefish_escript:load_conf/1 (/vernemq-build/_build/default/lib/cuttlefish/src/cuttlefish_escript.erl, line 307)
jalpine_morpheus |   in call from cuttlefish_escript:engage_cuttlefish/1 (/vernemq-build/_build/default/lib/cuttlefish/src/cuttlefish_escript.erl, line 361)
jalpine_morpheus |   in call from cuttlefish_escript:generate/1 (/vernemq-build/_build/default/lib/cuttlefish/src/cuttlefish_escript.erl, line 255)
```

I feel that  lines with whitespace should be accepted and ignored. 

I ran into this issue while debugging with VerneMQ for a different issue, and having edited the config file with nano. 

See also
https://pi3g.com/2019/06/04/debugging-vernemq-connection-authentication-problems-for-dual-authentication-with-webhooks-and-vmq_diversity/ (Bonus section)

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #1 

Thanks to @puresilk for the easy-to-follow reproduction steps.

### CODE REVIEW

File: src/conf_parse.erl [hunk 1]
```diff
@@ -91,20 +92,32 @@ file_test() ->
...
 -endif.
 
 -spec file(file:name()) -> any().
-file(Filename) ->
-    AbsFilename = filename:absname(Filename),
-    case erl_prim_loader:get_file(AbsFilename) of
-        {ok, Bin, _} -> parse(Bin);
-        error -> {error, undefined}
-    end.
+file(Filename) -> case file:read_file(Filename) of {ok,Bin} -> parse(Bin); Err -> Err end.
```
Comment (lukebakken) [inline src/conf_parse.erl]: @dumbbell I believe this was changed via the version of `neotoma` I'm using. I can revert it manually if necessary.

**Comment by puresilk** [comment]
Thank you very much for fixing the bug so quickly!

**Comment by michaelklishin** [comment]
`2.2.1` is up on Hex.
